FROM python:3.10.9
RUN pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
COPY requirements-dev.txt /tmp/requirements-dev.txt
RUN pip install -r /tmp/requirements-dev.txt

RUN apt update && apt install -y vim sqlite3

WORKDIR /opt/root-pythia
RUN mkdir logs

CMD ["bash"]
