FROM python:3.10.9
RUN pip install --upgrade pip

WORKDIR /opt/root-pythia
COPY watch.sh .
COPY requirements.txt /tmp/requirements.txt
COPY requirements-dev.txt /tmp/requirements-dev.txt
RUN pip install -r /tmp/requirements-dev.txt

ENTRYPOINT ["bash"]
CMD ["watch.sh"]
